version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf

  app:
    image: cr.yandex/crpa63e0skdhtni87735/backend:${TAG}
    ports:
      - "8080:8080"
    environment:
      PGPASSWORD: 1
    depends_on:
      - db
    command: >
      sh -c "sleep 10 && ./myapp"

volumes:
  postgres_data: