version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
    command: >
      sh -c "sleep 10 && psql -h db -U postgres -d postgres -c \"
            CREATE TABLE IF NOT EXISTS commands (
              id SERIAL PRIMARY KEY,
              title TEXT,
              content TEXT,
              exec_res TEXT
            );\""

volumes:
  postgres_data: