name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Set up Go 1.21
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Test
        run: go test -v ./...

  build_and_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: test

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Setup PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Create database table
        run: |
          PGPASSWORD=${{ secrets.POSTGRES_PASSWORD }} psql -h localhost -U postgres -d postgres -c "
          CREATE TABLE IF NOT EXISTS commands (
            id SERIAL PRIMARY KEY,
            title TEXT,
            content TEXT,
            exec_res TEXT
          );"


      - name: Install Yandex CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "export PATH=$PATH:$HOME/.yandex-cloud/bin" >> $GITHUB_ENV
          source "/home/runner/.bashrc

      - name: Log in to Yandex Cloud Container Registry
        run: |
          yc config profile create github-actions
          yc config set token ${{ secrets.YC_TOKEN }}
          yc container registry configure-docker

      - name: Build container image
        run: |
          docker build --build-arg DATABASE_URL=host=localhost port=5432 user=postgres password=${{ secrets.POSTGRES_PASSWORD }} dbname=postgres sslmode=disable -t cr.yandex/your-registry-id/my-server:${{ github.sha }} .

      - name: Push container image to Yandex Cloud
        run: |
          docker push cr.yandex/your-registry-id/my-server:${{ github.sha }}
