name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Set up Go 1.21
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Test
        run: go test -v ./...

  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    # needs: test

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      # - name: Login to Yandex Cloud Container Registry
      #   id: login-cr
      #   uses: yc-actions/yc-cr-login@v1
      #   with:
      #     yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      # - name: Build, tag, and push image to Yandex Cloud Container Registry
      #   env:
      #     CR_REGISTRY: crpa63e0skdhtni87735
      #     CR_REPOSITORY: backend
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
      #     docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

      # - name: Deploy COI VM
      #   id: deploy-coi
      #   uses: yc-actions/yc-coi-deploy@v2
      #   env:
      #     CR_REGISTRY: crpa63e0skdhtni87735
      #     CR_REPOSITORY: backend
      #     IMAGE_TAG: ${{ github.sha }}
      #   with:
      #     yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      #     folder-id: ${{ secrets.YC_FOLDER_ID }}
      #     vm-name: testvm
      #     vm-service-account-id: epdtc6j2rh93lrt4vqom
      #     vm-cores: 2
      #     vm-memory: 2Gb
      #     vm-core-fraction: 100
      #     vm-subnet-id: e2lmf84lhk5tekk3cqq1
      #     user-data-path: './user-data.yaml'
      #     docker-compose-path: './docker-compose.yaml'

      # - name: Deploy to Yandex Cloud VM
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.VM_IP }}
      #     username: 'your_vm_username'
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       docker pull cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
      #       docker stop my-app-instance || true
      #       docker rm my-app-instance || true
      #       docker run -d --name my-app-instance -p 80:80 cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
      #   env:
      #     CR_REGISTRY: crpa63e0skdhtni87735
      #     CR_REPOSITORY: backend
      #     IMAGE_TAG: ${{ github.sha }}

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o "StrictHostKeyChecking=no" ubuntu@${{ secrets.VM_IP }} "echo 'Hello' && echo 'test'"
